-- prospecta v0.1 canonical schema (schema.md §2).
-- Per ralplan: pgvector only (no pg_trgm); banks.fts_config removed;
-- dim-check trigger on memory_items; COMMENT ON COLUMN on spine columns.
-- Per-bank HNSW partial indexes are NOT created here — T4's create_bank() helper
-- builds them once embedding_dim is known.

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Migration bookkeeping
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS prospecta_schema_version (
    version       INTEGER PRIMARY KEY,
    applied_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    description   TEXT NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- banks
-- ---------------------------------------------------------------------------

CREATE TABLE banks (
    bank_id            TEXT PRIMARY KEY,
    config             JSONB NOT NULL DEFAULT '{}'::jsonb,
    mission            TEXT,
    retain_mission     TEXT,
    embedding_dim      INTEGER NOT NULL,
    embedding_model_id TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX banks_created_at_idx ON banks(created_at);

COMMENT ON COLUMN banks.embedding_dim IS
    'Per-bank vector dimensionality. Locked at create_bank time. Migration to new dim requires new bank.';

-- ---------------------------------------------------------------------------
-- documents
-- ---------------------------------------------------------------------------

CREATE TABLE documents (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bank_id            TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    source             TEXT,
    original_text      TEXT NOT NULL,
    content_hash       TEXT NOT NULL,
    tags               TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    document_metadata  JSONB NOT NULL DEFAULT '{}'::jsonb,
    retain_params      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (bank_id, content_hash)
);

CREATE INDEX documents_bank_source_idx ON documents(bank_id, source);
CREATE INDEX documents_tags_gin        ON documents USING GIN(tags);
CREATE INDEX documents_created_at_idx  ON documents(bank_id, created_at DESC);

COMMENT ON COLUMN documents.original_text IS
    'Source-of-truth for retained content. Preserved across re-retain (P5).';
COMMENT ON COLUMN documents.content_hash IS
    'For dedup. UNIQUE (bank_id, content_hash) drives replace-on-source-match semantics.';
COMMENT ON COLUMN documents.source IS
    'Caller-supplied identifier for the originating source (file path, URL, conversation ID). Used by replace-on-source-match for re-retain.';

-- ---------------------------------------------------------------------------
-- memory_items (the spine)
-- ---------------------------------------------------------------------------

CREATE TABLE memory_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bank_id         TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    document_id     UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

    -- Spine columns (P1)
    content         TEXT NOT NULL,
    original_chunk  TEXT NOT NULL,
    embedding       vector NOT NULL,
    content_tsv     tsvector
                    GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,

    -- Provenance + filtering
    context         TEXT,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    tags            TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    update_mode     TEXT NOT NULL DEFAULT 'append',
    llm_generated   BOOLEAN NOT NULL DEFAULT FALSE,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX memory_items_bank_time_idx ON memory_items(bank_id, created_at DESC);
CREATE INDEX memory_items_doc_idx       ON memory_items(document_id);
CREATE INDEX memory_items_tsv_gin       ON memory_items USING GIN(content_tsv);
CREATE INDEX memory_items_tags_gin      ON memory_items USING GIN(tags);

COMMENT ON COLUMN memory_items.content IS
    'Bilateral spine: LLM-anticipated question form. The embedded text in the semantic index.';
COMMENT ON COLUMN memory_items.original_chunk IS
    'Source text the index_text indexes (P5 no-truncation; full audit trail).';
COMMENT ON COLUMN memory_items.embedding IS
    'Vector representation of `content`. Dimensionality must match the bank''s embedding_dim. Generated by caller-supplied embed() callable.';
COMMENT ON COLUMN memory_items.content_tsv IS
    'STORED generated column: to_tsvector(''english'', content). Indexed via GIN for the lexical half of hybrid retrieval (BM25 fallback when LLM-anticipated index_text drifts).';
COMMENT ON COLUMN memory_items.llm_generated IS
    'True if index_text was LLM-generated; False if caller-supplied (P4 caller-wins audit).';

-- ---------------------------------------------------------------------------
-- Dim-check trigger (A2)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION assert_memory_item_embedding_dim() RETURNS trigger AS $$
DECLARE
    expected_dim INTEGER;
    actual_dim   INTEGER;
BEGIN
    SELECT embedding_dim INTO expected_dim FROM banks WHERE bank_id = NEW.bank_id;
    IF expected_dim IS NULL THEN
        RAISE EXCEPTION 'memory_items.bank_id = % has no banks row', NEW.bank_id;
    END IF;
    actual_dim := vector_dims(NEW.embedding);
    IF actual_dim <> expected_dim THEN
        RAISE EXCEPTION
            'memory_items.embedding dim mismatch for bank %: expected %, got %',
            NEW.bank_id, expected_dim, actual_dim;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER memory_items_embedding_dim_check
    BEFORE INSERT OR UPDATE OF embedding, bank_id ON memory_items
    FOR EACH ROW EXECUTE FUNCTION assert_memory_item_embedding_dim();

-- ---------------------------------------------------------------------------
-- Event tables
-- ---------------------------------------------------------------------------

CREATE TABLE retain_events (
    id                          BIGSERIAL PRIMARY KEY,
    bank_id                     TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    document_id                 UUID REFERENCES documents(id) ON DELETE SET NULL,
    items_count                 INTEGER NOT NULL,
    index_text_caller_supplied  BOOLEAN NOT NULL,
    duration_ms                 INTEGER NOT NULL,
    raw_llm_response            TEXT,
    error                       TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX retain_events_bank_time_idx ON retain_events(bank_id, created_at DESC);

CREATE TABLE recall_events (
    id                BIGSERIAL PRIMARY KEY,
    bank_id           TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    queries           JSONB NOT NULL,
    mode              TEXT NOT NULL,
    n_results         INTEGER NOT NULL,
    duration_ms       INTEGER NOT NULL,
    query_timestamp   TIMESTAMPTZ,
    trace             JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX recall_events_bank_time_idx ON recall_events(bank_id, created_at DESC);

CREATE TABLE formulate_events (
    id              BIGSERIAL PRIMARY KEY,
    bank_id         TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    message         TEXT NOT NULL,
    n_queries_out   INTEGER NOT NULL,
    json_mode_used  BOOLEAN NOT NULL,
    parse_fallback  BOOLEAN NOT NULL,
    raw_response    TEXT NOT NULL,
    duration_ms     INTEGER NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX formulate_events_bank_time_idx ON formulate_events(bank_id, created_at DESC);

CREATE TABLE llm_calls (
    id              BIGSERIAL PRIMARY KEY,
    bank_id         TEXT REFERENCES banks(bank_id) ON DELETE SET NULL,
    prompt_name     TEXT NOT NULL,
    messages_count  INTEGER NOT NULL,
    json_mode       BOOLEAN NOT NULL,
    duration_ms     INTEGER NOT NULL,
    error           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX llm_calls_bank_time_idx   ON llm_calls(bank_id, created_at DESC);
CREATE INDEX llm_calls_prompt_time_idx ON llm_calls(prompt_name, created_at DESC);

-- A4: append-only sweep history
CREATE TABLE sweep_passes (
    id              BIGSERIAL PRIMARY KEY,
    bank_id         TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    corpus_path     TEXT NOT NULL,
    started_at      TIMESTAMPTZ NOT NULL,
    ended_at        TIMESTAMPTZ,
    files_seen      INTEGER NOT NULL DEFAULT 0,
    files_indexed   INTEGER NOT NULL DEFAULT 0,
    files_pruned    INTEGER NOT NULL DEFAULT 0,
    errors_count    INTEGER NOT NULL DEFAULT 0,
    duration_ms     INTEGER,
    error           TEXT,
    pass_metadata   JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX sweep_passes_bank_time_idx ON sweep_passes(bank_id, started_at DESC);
CREATE INDEX sweep_passes_corpus_idx    ON sweep_passes(bank_id, corpus_path, started_at DESC);

CREATE TABLE sweeper_state (
    bank_id                  TEXT NOT NULL REFERENCES banks(bank_id) ON DELETE CASCADE,
    corpus_path              TEXT NOT NULL,
    last_pass_started_at     TIMESTAMPTZ,
    last_pass_ended_at       TIMESTAMPTZ,
    last_pass_files_seen     INTEGER,
    last_pass_files_indexed  INTEGER,
    last_pass_files_pruned   INTEGER,
    last_pass_errors         INTEGER,
    last_pass_duration_ms    INTEGER,
    last_error               TEXT,
    PRIMARY KEY (bank_id, corpus_path)
);
